class NoteBase(BaseModel):
    title: str
    summary: str
    priority: Priority = Priority.MEDIUM
    status: NoteStatus = NoteStatus.PENDING

class NoteCreate(NoteBase):
    user_id: str
    transcript: str
    transcript_groq: str = ""
    transcript_deepgram: str = ""
    transcript_elevenlabs: str = ""
    transcript_android: str = ""
    audio_url: Optional[str] = None
    raw_audio_url: Optional[str] = None
    document_urls: List[str] = []
    links: List[ExternalLink] = []
    is_encrypted: bool = False
    comparison_notes: str = ""

class NoteResponse(NoteBase):
    id: str
    timestamp: int
    transcript: str
    audio_url: Optional[str]
    tasks: List[TaskResponse]
    is_pinned: bool
    is_liked: bool
    is_archived: bool
    model_config = ConfigDict(from_attributes=True)

class NoteAIOutput(BaseModel):
    """Schema for the JSON object generated by Llama 3.1"""
    title: str
    summary: str
    priority: Priority
    transcript: str  # Formatted with speaker labels
    tasks: List[TaskBase]