from typing import List, Optional

from pydantic import BaseModel, ConfigDict

from app.db.models import NoteStatus, Priority


class ExternalLink(BaseModel):
    url: str
    title: Optional[str] = None


class NoteBase(BaseModel):
    title: str
    summary: str
    priority: Priority = Priority.MEDIUM
    status: NoteStatus = NoteStatus.PENDING


class NoteCreate(NoteBase):
    user_id: str
    transcript: str
    transcript_groq: str = ""
    transcript_deepgram: str = ""
    transcript_elevenlabs: str = ""
    transcript_android: str = ""
    audio_url: Optional[str] = None
    raw_audio_url: Optional[str] = None
    document_uris: List[str] = []  # Client-side URIs
    image_uris: List[str] = []  # Client-side image URIs
    links: List[ExternalLink] = []
    is_encrypted: bool = False
    comparison_notes: str = ""


class NoteUpdate(BaseModel):
    """Schema for updating notes - all fields optional"""

    title: Optional[str] = None
    summary: Optional[str] = None
    priority: Optional[Priority] = None
    status: Optional[NoteStatus] = None
    is_pinned: Optional[bool] = None
    is_liked: Optional[bool] = None
    is_archived: Optional[bool] = None
    transcript: Optional[str] = None
    document_uris: Optional[List[str]] = None  # Client-side URIs
    image_uris: Optional[List[str]] = None  # Client-side image URIs
    links: Optional[List[ExternalLink]] = None
    is_deleted: Optional[bool] = None
    model_config = ConfigDict(from_attributes=True)


class TaskSummary(BaseModel):
    id: str
    title: Optional[str] = None
    description: str
    is_done: bool
    priority: Priority
    actions: Optional[dict] = None
    model_config = ConfigDict(from_attributes=True)


class NoteResponseSummary(BaseModel):
    """Minimal representation of a note for lists/previews"""

    id: str
    title: str
    timestamp: int
    model_config = ConfigDict(from_attributes=True)


class NoteResponse(NoteBase):
    id: str
    user_id: str
    timestamp: int
    updated_at: int
    transcript: str
    audio_url: Optional[str]
    raw_audio_url: Optional[str]
    document_uris: List[str] = []  # Client-side URIs
    image_uris: List[str] = []  # Client-side image URIs
    links: List[ExternalLink] = []
    tasks: List[TaskSummary] = []  # Typed list for Pydantic validation
    is_pinned: bool
    is_liked: bool
    is_archived: bool
    is_deleted: bool
    deleted_at: Optional[int] = None
    is_encrypted: bool = False
    tags: List[str] = []
    semantic_analysis: Optional[dict] = None
    processing_time_ms: Optional[int] = None  # New: Time taken for AI analysis
    related_notes: List[NoteResponseSummary] = []  # NEW: Top 3 semantic links
    model_config = ConfigDict(from_attributes=True)


class NoteAIOutput(BaseModel):
    """Schema for the JSON object generated by Llama 3.1"""

    title: str
    summary: str
    priority: Priority
    transcript: str  # Formatted with speaker labels
    tasks: List[dict] = []  # Avoid circular import
    tags: List[str] = []  # New
    metadata: Optional[dict] = None


class NoteSemanticAnalysis(BaseModel):
    """Schema for deep semantic insights"""

    sentiment: str
    key_insights: List[str]
    logical_patterns: List[str]
    suggested_questions: List[str]
    emotional_tone: str
    actionable_hidden_tasks: List[str]


class SearchQuery(BaseModel):
    query: str
    limit: Optional[int] = 10
    offset: Optional[int] = 0


class TopicHeatmapItem(BaseModel):
    topic: str
    count: int


class DashboardResponse(BaseModel):
    task_velocity: float
    completed_tasks: int
    total_tasks: int
    topic_heatmap: List[TopicHeatmapItem]
    meeting_roi_hours: float
    recent_notes_count: int
    status: str
