"""Add conflicts column to Note

Revision ID: 084ddc24f5cd
Revises: bdb0e0fff465
Create Date: 2026-02-15 22:49:17.949982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '084ddc24f5cd'
down_revision: Union[str, Sequence[str], None] = 'bdb0e0fff465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'conflicts')
    # ### end Alembic commands ###
