"""Add admin action log table

Revision ID: 1381be85f606
Revises: d2c4ef74bfb7
Create Date: 2026-02-05 11:57:15.495552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1381be85f606'
down_revision: Union[str, Sequence[str], None] = 'd2c4ef74bfb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('updated_by', sa.String(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'updated_by')
    # ### end Alembic commands ###
