"""add_suggested_actions_to_tasks

Revision ID: 27a3b82897cf
Revises: 9c5ef8660570
Create Date: 2026-02-03 03:32:24.797904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27a3b82897cf'
down_revision: Union[str, Sequence[str], None] = '9c5ef8660570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('suggested_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'suggested_actions')
    # ### end Alembic commands ###
