"""add tags to notes

Revision ID: 2c7e9e95026f
Revises: 5041fce47ec5
Create Date: 2026-02-07 03:06:06.018193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c7e9e95026f'
down_revision: Union[str, Sequence[str], None] = '5041fce47ec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_column('notes', 'tags')
    # ### end Alembic commands ###
