"""drop transcript_android column

Revision ID: 4803618194b2
Revises: 084ddc24f5cd
Create Date: 2026-02-22 15:02:38.000127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4803618194b2'
down_revision: Union[str, Sequence[str], None] = '084ddc24f5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'transcript_android')
    op.create_index('idx_tasks_note_priority', 'tasks', ['note_id', 'priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tasks_note_priority', table_name='tasks')
    op.add_column('notes', sa.Column('transcript_android', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
