"""Add processing_time_ms to notes

Revision ID: 5eabacb91235
Revises: b891cb8863b5
Create Date: 2026-02-14 18:09:42.056383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eabacb91235'
down_revision: Union[str, Sequence[str], None] = 'b891cb8863b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type manually if it doesn't exist
    task_status = sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='taskstatus')
    task_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('admin_user_id', sa.String(), nullable=True),
    sa.Column('corporate_wallet_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_table('folders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_folders_user_id'), 'folders', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_integrations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.BigInteger(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_integrations_provider'), 'user_integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_user_integrations_user_id'), 'user_integrations', ['user_id'], unique=False)
    op.create_table('work_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('org_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folder_participants',
    sa.Column('folder_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('joined_at', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'user_id')
    )
    op.add_column('notes', sa.Column('folder_id', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('notes', sa.Column('processing_time_ms', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_notes_folder_id'), 'notes', ['folder_id'], unique=False)
    op.create_index('ix_notes_tags', 'notes', ['tags'], unique=False, postgresql_using='gin')
    op.create_foreign_key(None, 'notes', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.add_column('tasks', sa.Column('title', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='taskstatus'), nullable=True))
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.add_column('users', sa.Column('profile_picture_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('org_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['org_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'org_id')
    op.drop_column('users', 'profile_picture_url')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'title')
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_index('ix_notes_tags', table_name='notes', postgresql_using='gin')
    op.drop_index(op.f('ix_notes_folder_id'), table_name='notes')
    op.drop_column('notes', 'processing_time_ms')
    op.drop_column('notes', 'tags')
    op.drop_column('notes', 'folder_id')
    op.drop_table('folder_participants')
    op.drop_table('work_locations')
    op.drop_index(op.f('ix_user_integrations_user_id'), table_name='user_integrations')
    op.drop_index(op.f('ix_user_integrations_provider'), table_name='user_integrations')
    op.drop_table('user_integrations')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_folders_user_id'), table_name='folders')
    op.drop_table('folders')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
