"""Add processing_time_ms to notes

Revision ID: 5eabacb91235
Revises: b891cb8863b5
Create Date: 2026-02-14 18:09:42.056383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eabacb91235'
down_revision: Union[str, Sequence[str], None] = 'b891cb8863b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create the Enum type manually if it doesn't exist
    task_status = sa.Enum('TODO', 'IN_PROGRESS', 'DONE', 'BLOCKED', name='taskstatus')
    task_status.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('processing_time_ms', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'processing_time_ms')
    # ### end Alembic commands ###
