"""add_missing_user_columns

Revision ID: 67e2253fc857
Revises: e7cb3d806486
Create Date: 2026-01-28 11:28:35.947194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = '67e2253fc857'
down_revision: Union[str, Sequence[str], None] = 'e7cb3d806486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()

    if 'api_keys' not in tables:
        op.create_table('api_keys',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('service_name', sa.String(length=50), nullable=False),
        sa.Column('api_key', sa.Text(), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
        sa.Column('rate_limit_reset_at', sa.BigInteger(), nullable=True),
        sa.Column('last_used_at', sa.BigInteger(), nullable=True),
        sa.Column('last_error_at', sa.BigInteger(), nullable=True),
        sa.Column('error_count', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('service_name', 'priority', name='uq_service_priority')
        )
    
    if 'users' not in tables:
        op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('authorized_devices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('current_device_id', sa.String(), nullable=True),
        sa.Column('tier', sa.Enum('FREE', 'STANDARD', 'PREMIUM', name='subscriptiontier'), nullable=True),
        sa.Column('password_hash', sa.String(), nullable=True),
        sa.Column('last_login', sa.BigInteger(), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.BigInteger(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.Column('deletion_reason', sa.String(), nullable=True),
        sa.Column('can_restore', sa.Boolean(), nullable=True),
        sa.Column('primary_role', sa.Enum('STUDENT', 'TEACHER', 'DEVELOPER', 'OFFICE_WORKER', 'BUSINESS_MAN', 'PSYCHIATRIST', 'PSYCHOLOGIST', 'GENERIC', name='userrole'), nullable=True),
        sa.Column('secondary_role', sa.Enum('STUDENT', 'TEACHER', 'DEVELOPER', 'OFFICE_WORKER', 'BUSINESS_MAN', 'PSYCHIATRIST', 'PSYCHOLOGIST', 'GENERIC', name='userrole'), nullable=True),
        sa.Column('custom_role_description', sa.Text(), nullable=True),
        sa.Column('system_prompt', sa.Text(), nullable=True),
        sa.Column('jargons', sa.JSON(), nullable=True),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('admin_permissions', sa.JSON(), nullable=True),
        sa.Column('admin_created_at', sa.BigInteger(), nullable=True),
        sa.Column('admin_last_action', sa.BigInteger(), nullable=True),
        sa.Column('show_floating_button', sa.Boolean(), nullable=True),
        sa.Column('work_start_hour', sa.Integer(), nullable=True),
        sa.Column('work_end_hour', sa.Integer(), nullable=True),
        sa.Column('work_days', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
        op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    else:
        # Table exists, add missing columns safely
        existing_cols = [c['name'] for c in inspector.get_columns('users')]
        if 'authorized_devices' not in existing_cols:
            op.add_column('users', sa.Column('authorized_devices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        if 'is_admin' not in existing_cols:
            op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
            op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
        if 'primary_role' not in existing_cols:
            # Create enum type if not exists
            # op.execute("DO $$ BEGIN CREATE TYPE userrole AS ENUM ('STUDENT', 'TEACHER', 'DEVELOPER', 'OFFICE_WORKER', 'BUSINESS_MAN', 'PSYCHIATRIST', 'PSYCHOLOGIST', 'GENERIC'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
            op.add_column('users', sa.Column('primary_role', sa.Enum('STUDENT', 'TEACHER', 'DEVELOPER', 'OFFICE_WORKER', 'BUSINESS_MAN', 'PSYCHIATRIST', 'PSYCHOLOGIST', 'GENERIC', name='userrole'), nullable=True))
        if 'tier' not in existing_cols:
             op.add_column('users', sa.Column('tier', sa.Enum('FREE', 'STANDARD', 'PREMIUM', name='subscriptiontier'), nullable=True))
        if 'work_start_hour' not in existing_cols:
             op.add_column('users', sa.Column('work_start_hour', sa.Integer(), nullable=True))

    if 'notes' not in tables:
        op.create_table('notes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('transcript_groq', sa.Text(), nullable=True),
        sa.Column('transcript_deepgram', sa.Text(), nullable=True),
        sa.Column('transcript_android', sa.Text(), nullable=True),
        sa.Column('audio_url', sa.String(), nullable=True),
        sa.Column('raw_audio_url', sa.String(), nullable=True),
        sa.Column('timestamp', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
        sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'DONE', 'DELAYED', name='notestatus'), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.BigInteger(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.Column('deletion_reason', sa.Text(), nullable=True),
        sa.Column('can_restore', sa.Boolean(), nullable=True),
        sa.Column('is_pinned', sa.Boolean(), nullable=True),
        sa.Column('is_liked', sa.Boolean(), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=True),
        sa.Column('is_encrypted', sa.Boolean(), nullable=True),
        sa.Column('document_urls', sa.JSON(), nullable=True),
        sa.Column('links', sa.JSON(), nullable=True),
        sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
        sa.Column('embedding_version', sa.Integer(), nullable=True),
        sa.Column('semantic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('ai_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_notes_embedding', 'notes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
        op.create_index(op.f('ix_notes_is_deleted'), 'notes', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    else:
         existing_cols = [c['name'] for c in inspector.get_columns('notes')]
         if 'transcript_groq' not in existing_cols:
             op.add_column('notes', sa.Column('transcript_groq', sa.Text(), nullable=True))
         if 'semantic_analysis' not in existing_cols:
             op.add_column('notes', sa.Column('semantic_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
         if 'ai_responses' not in existing_cols:
             op.add_column('notes', sa.Column('ai_responses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
         if 'document_urls' not in existing_cols:
             op.add_column('notes', sa.Column('document_urls', sa.JSON(), nullable=True))
         if 'embedding' not in existing_cols:
             op.add_column('notes', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
             op.create_index('idx_notes_embedding', 'notes', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    if 'system_settings' not in tables:
        op.create_table('system_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('llm_model', sa.String(length=100), nullable=True),
        sa.Column('llm_fast_model', sa.String(length=100), nullable=True),
        sa.Column('temperature', sa.Integer(), nullable=True),
        sa.Column('max_tokens', sa.Integer(), nullable=True),
        sa.Column('top_p', sa.Integer(), nullable=True),
        sa.Column('stt_engine', sa.String(length=50), nullable=True),
        sa.Column('groq_whisper_model', sa.String(length=100), nullable=True),
        sa.Column('deepgram_model', sa.String(length=50), nullable=True),
        sa.Column('semantic_analysis_prompt', sa.Text(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_by', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if 'usage_logs' not in tables:
        op.create_table('usage_logs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('endpoint', sa.String(), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('tokens_input', sa.Integer(), nullable=True),
        sa.Column('tokens_output', sa.Integer(), nullable=True),
        sa.Column('provider', sa.String(), nullable=True),
        sa.Column('model', sa.String(), nullable=True),
        sa.Column('cost_estimated', sa.Integer(), nullable=True),
        sa.Column('status', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_usage_logs_endpoint'), 'usage_logs', ['endpoint'], unique=False)
        op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    if 'wallets' not in tables:
        op.create_table('wallets',
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('balance', sa.Integer(), nullable=True),
        sa.Column('currency', sa.String(length=3), nullable=True),
        sa.Column('is_frozen', sa.Boolean(), nullable=True),
        sa.Column('stripe_customer_id', sa.String(), nullable=True),
        sa.Column('stripe_subscription_id', sa.String(), nullable=True),
        sa.Column('auto_recharge_enabled', sa.Boolean(), nullable=True),
        sa.Column('recharge_threshold', sa.Integer(), nullable=True),
        sa.Column('recharge_amount', sa.Integer(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
        )
        op.create_index(op.f('ix_wallets_stripe_customer_id'), 'wallets', ['stripe_customer_id'], unique=False)
    if 'tasks' not in tables:
        op.create_table('tasks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('note_id', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_done', sa.Boolean(), nullable=True),
        sa.Column('deadline', sa.BigInteger(), nullable=True),
        sa.Column('priority', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='priority'), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('deleted_at', sa.BigInteger(), nullable=True),
        sa.Column('deleted_by', sa.String(), nullable=True),
        sa.Column('deletion_reason', sa.Text(), nullable=True),
        sa.Column('can_restore', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.Column('updated_at', sa.BigInteger(), nullable=True),
        sa.Column('notified_at', sa.BigInteger(), nullable=True),
        sa.Column('reminder_count', sa.Integer(), nullable=True),
        sa.Column('notification_enabled', sa.Boolean(), nullable=True),
        sa.Column('assigned_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('document_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('external_links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('communication_type', sa.Enum('WHATSAPP', 'SMS', 'CALL', 'MEET', 'SLACK', name='communicationtype'), nullable=True),
        sa.Column('is_action_approved', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_tasks_is_deleted'), 'tasks', ['is_deleted'], unique=False)
        op.create_index(op.f('ix_tasks_note_id'), 'tasks', ['note_id'], unique=False)
    else:
        existing_cols = [c['name'] for c in inspector.get_columns('tasks')]
        if 'assigned_entities' not in existing_cols:
             op.add_column('tasks', sa.Column('assigned_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        if 'image_urls' not in existing_cols:
             op.add_column('tasks', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        if 'notification_enabled' not in existing_cols:
             op.add_column('tasks', sa.Column('notification_enabled', sa.Boolean(), nullable=True))
    if 'transactions' not in tables:
        op.create_table('transactions',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('wallet_id', sa.String(), nullable=True),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('balance_after', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=20), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('reference_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(['wallet_id'], ['wallets.user_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_tasks_note_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_deleted'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_wallets_stripe_customer_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_endpoint'), table_name='usage_logs')
    op.drop_table('usage_logs')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_deleted'), table_name='notes')
    op.drop_index('idx_notes_embedding', table_name='notes', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('notes')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
