"""final_schema_sync_and_is_new_user_logic

Revision ID: d2c4ef74bfb7
Revises: add_guest_enum
Create Date: 2026-02-05 12:55:18.653796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2c4ef74bfb7'
down_revision: Union[str, Sequence[str], None] = 'add_guest_enum'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    
    # Safely handle notes table columns
    note_columns = [c['name'] for c in inspector.get_columns('notes')]
    
    # Handle document_uris / document_urls
    if 'document_uris' in note_columns:
        op.alter_column('notes', 'document_uris',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
    elif 'document_urls' in note_columns:
        op.execute("ALTER TABLE notes RENAME COLUMN document_urls TO document_uris")
        op.alter_column('notes', 'document_uris',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
    else:
        op.add_column('notes', sa.Column('document_uris', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Handle links
    if 'links' in note_columns:
        op.alter_column('notes', 'links',
                   existing_type=postgresql.JSON(astext_type=sa.Text()),
                   type_=postgresql.JSONB(astext_type=sa.Text()),
                   existing_nullable=True)
    else:
        op.add_column('notes', sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('notes', 'document_uris',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
