"""Initial migration

Revision ID: e7cb3d806486
Revises: 
Create Date: 2026-01-24 17:39:25.230701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cb3d806486'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    # 1. Alter Column id if table exists
    if 'api_keys' in tables:
        op.alter_column('api_keys', 'id',
                   existing_type=sa.UUID(),
                   type_=sa.String(),
                   existing_nullable=False,
                   existing_server_default=sa.text('uuid_generate_v4()'))
                   
        # 2. Drop constraint if exists
        constraints = inspector.get_unique_constraints('api_keys')
        constraint_names = [c['name'] for c in constraints]
        
        # Check for automatically generated name or explicit name
        target_constraint = 'api_keys_service_name_priority_key'
        if target_constraint in constraint_names:
            op.drop_constraint(target_constraint, 'api_keys', type_='unique')
        
        # Check for idx
        indexes = inspector.get_indexes('api_keys')
        index_names = [i['name'] for i in indexes]
        if 'idx_api_keys_service_active' in index_names:
            op.drop_index('idx_api_keys_service_active', table_name='api_keys')
            
        # 3. Create unique constraint
        if 'uq_service_priority' not in constraint_names:
            op.create_unique_constraint('uq_service_priority', 'api_keys', ['service_name', 'priority'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_service_priority', 'api_keys', type_='unique')
    op.create_index(op.f('idx_api_keys_service_active'), 'api_keys', ['service_name', 'is_active', 'priority'], unique=False)
    op.create_unique_constraint(op.f('api_keys_service_name_priority_key'), 'api_keys', ['service_name', 'priority'], postgresql_nulls_not_distinct=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    # ### end Alembic commands ###
