"""notes model index

Revision ID: eb0754a08322
Revises: a1b2c3d4e5f6
Create Date: 2026-02-23 11:39:34.860110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0754a08322'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_notes_team_timestamp', 'notes', ['team_id', 'timestamp'], unique=False)
    op.create_index('idx_notes_user_timestamp', 'notes', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notes_user_timestamp', table_name='notes')
    op.drop_index('idx_notes_team_timestamp', table_name='notes')
    # ### end Alembic commands ###
