"""separate_guest_tier_from_job_role

Revision ID: fbbcc1ae10ef
Revises: f0ce123_force
Create Date: 2026-02-01 12:20:31.449576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbbcc1ae10ef'
down_revision: Union[str, Sequence[str], None] = 'f0ce123_force'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_priority'), 'notes', ['priority'], unique=False)
    op.create_index(op.f('ix_notes_status'), 'notes', ['status'], unique=False)
    op.create_index(op.f('ix_notes_timestamp'), 'notes', ['timestamp'], unique=False)
    op.drop_constraint(op.f('system_settings_updated_by_fkey'), 'system_settings', type_='foreignkey')
    op.create_foreign_key(None, 'system_settings', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_tasks_deadline'), 'tasks', ['deadline'], unique=False)
    op.create_index(op.f('ix_tasks_is_done'), 'tasks', ['is_done'], unique=False)
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    op.drop_constraint(op.f('transactions_wallet_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('usage_logs_user_id_fkey'), 'usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'usage_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'jargons',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'work_days',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'work_days',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'jargons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'usage_logs', type_='foreignkey')
    op.create_foreign_key(op.f('usage_logs_user_id_fkey'), 'usage_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_wallet_id_fkey'), 'transactions', 'wallets', ['wallet_id'], ['user_id'])
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_done'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deadline'), table_name='tasks')
    op.drop_constraint(None, 'system_settings', type_='foreignkey')
    op.create_foreign_key(op.f('system_settings_updated_by_fkey'), 'system_settings', 'users', ['updated_by'], ['id'])
    op.drop_index(op.f('ix_notes_timestamp'), table_name='notes')
    op.drop_index(op.f('ix_notes_status'), table_name='notes')
    op.drop_index(op.f('ix_notes_priority'), table_name='notes')
    # ### end Alembic commands ###
